"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.STEP_FORWARD_PRESERVING_ERRORS = exports.SET_ERROR = exports.STEP_BACK = exports.STEP_FORWARD = exports.DESTROY = exports.INITIALIZE = void 0;

/**
 * Created by rouven on 13.06.17.
 */
var PREFIX = '@@wikom-wizard/';
var INITIALIZE = PREFIX + 'INITIALIZE';
exports.INITIALIZE = INITIALIZE;
var DESTROY = PREFIX + 'DESTROY';
exports.DESTROY = DESTROY;
var STEP_FORWARD = PREFIX + 'STEP_FORWARD';
exports.STEP_FORWARD = STEP_FORWARD;
var STEP_BACK = PREFIX + 'STEP_BACK';
exports.STEP_BACK = STEP_BACK;
var SET_ERROR = PREFIX + 'SET_ERROR';
exports.SET_ERROR = SET_ERROR;
var STEP_FORWARD_PRESERVING_ERRORS = PREFIX + 'STEP_FORWARD_PRESERVING_ERRORS';
exports.STEP_FORWARD_PRESERVING_ERRORS = STEP_FORWARD_PRESERVING_ERRORS;